version: '3'

networks:
  my_network:
    driver: bridge

services:

  mysql-database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: service_reservation
    ports:
      - "3306:3306"
    networks:
      - my_network

  event-service:
    image: openjdk:17
    build:
      context: ./POV-JAVA/microservice-event-spring
    ports:
      - "6661:6661"

    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql-database:3306/service_event?createDatabaseIfNotExist=true&serverTimezone=UTC"
    depends_on:
      - mysql-database
    networks:
      - my_network

  reservation-service:
    image: openjdk:17
    ports:
      - "6662:6662"
    build:
      context: ./POV-JAVA/microserice-reservation-spring

    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql-database:3306/service_event?createDatabaseIfNotExist=true&serverTimezone=UTC"
    depends_on:
      - mysql-database
    networks:
      - my_network
